In [2]:
import pandas as pd

DB from @JoeSchroeNFT:

https://docs.google.com/spreadsheets/d/1uj_RkwcraJZc0cJitcf9lvBJjnz-vveWdfiV8lgljC8/edit#gid=0

In [5]:
sheet_id = '1uj_RkwcraJZc0cJitcf9lvBJjnz-vveWdfiV8lgljC8'
sheet_name = 'Ballerz%20Database'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [6]:
dat=pd.read_csv(url)

In [14]:
l=['ID',
   'Body',
   'Team',
   'Gender',
   'Accessory Group',
   'Accessory 1',
   'Accessory 2',
   'Accessory 3',
   'Jersey',
   'Hair',
   'Role',
   'Number',
   'Dunks',
   'Shooting',
   'Playmaking',
   'Defense',
   'Overall',
   'Pts',
   'Reb',
   'Ast',
   'Stl',
   'MVP?',
   'JSA Rarity Score',
   'JSA Rarity Rank']

dat_clean=dat[l].fillna('')
dat_clean.head(3)

,ID,Body,Team,Gender,Accessory Group,Accessory 1,Accessory 2,Accessory 3,Jersey,Hair,...,Playmaking,Defense,Overall,Pts,Reb,Ast,Stl,MVP?,JSA Rarity Score,JSA Rarity Rank
0,7353,Human,All-Stars,M,None,None,,,Home,Custom,...,99,99,99.0,40.0,16.0,14.0,4.0,True,742.68,1
1,2284,Human,All-Stars,M,None,None,,,Home,Custom,...,99,99,99.0,40.0,16.0,14.0,4.0,True,742.49,2
2,5316,Human,All-Stars,M,None,None,,,Home,Custom,...,99,99,99.0,40.0,16.0,14.0,4.0,True,742.49,2

In [ ]:
dat_clean.to_csv('~/your/dir')